### PR TITLE
fix(index): don't throw on empty tree (`options.skipParse`)

### LINKED ISSUE #244: [fix]: process fail
```js
posthtml().process(null, {parseSkip: true})
```

### PR DESCRIPTION
**Pull request by michael-ciniawsky**
### `Issues`

- Fixes #244

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
It should maybe fail tbh

File: lib/index.js [hunk 1]
```diff
@@ -94,7 +94,9 @@ PostHTML.prototype.process = function (tree, options) {
   if (options.parser) parser = options.parser
   if (options.render) render = options.render
 
-  tree = options.skipParse ? tree : parser(tree, options)
+  tree = options.skipParse
+    ? tree || []
```
Comment (voischev) [inline lib/index.js]: 👍
